version: '2'
services:
    elasticsearch:
        image: diabol/elasticsearch
        ports:
            - "${ELASTICPORT1}:9200"
            - "${ELASTICPORT2}:9300"
        volumes:
            - ${ELASTICDATA}:/opt/elasticsearch/data
            - ${ELASTICLOGS}:/opt/elasticsearch/logs
            - ./elasticsearch/config:/opt/elasticsearch/config
    kibana:
        image: diabol/kibana
        ports:
            - "${KIBANAPORT}:5601"
        volumes:
            - ./kibana/config:/opt/kibana/config
        depends_on:
            - elasticsearch    
    logstash:
        image: diabol/logstash
        volumes:
            - ./logstash/config/:/opt/logstash/config/
            - ./logstash/demologs:/tmp/demologs
        command: [/opt/logstash/bin/logstash,-f,/opt/logstash/config/demo.conf]
        depends_on:
            - elasticsearch
